version: '3.5'

services:

  front-web-prod:
    container_name: front-web-prod
    build:
      context: ./frontends/web
      dockerfile: Dockerfile-prod
    ports:
      - '80:80'
  
  gateway-web-prod:
    container_name: gateway-web-prod
    build:
      context: ./gateways/web
      dockerfile: Dockerfile-prod
    ports:
      - '3001:3001'