version: "3.5"

services:
  # frontend-web:port:3000
  # gateway-web:port:3001
  # services-users:port:3002
  # database-main:port:5432

  front-web:
    container_name: front-web
    build:
      context: ./frontends/web
      dockerfile: Dockerfile
    volumes:
      - "./frontends/web:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    links:
      - gateway-web
    depends_on:
      - gateway-web

  gateway-web:
    container_name: gateway-web
    build:
      context: ./gateways/web
      dockerfile: Dockerfile
    volumes:
      - "./gateways/web:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  service-users:
    build: ./services/users
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database-main:5432/maindev?sslmode=disable
      - JWT_SECRET=changeme
    volumes:
      - ./services/users:/go/src/users
    depends_on:
      - database-main
    links:
      - database-main

  database-main:
    build: ./databases/main-dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0
