FROM node:11-alpine

# set working directory
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# copy package to be installed in compose file
COPY package.json /usr/src/app/package.json

# install dependencies
RUN npm install --only=production

# start app
CMD ["node", "."]