FROM node:carbon AS base
# Create app directory
WORKDIR /usr/src/app

# ---- Dependencies ----
FROM base AS dependencies  
# A wildcard is used to ensure both package.json AND package-lock.json are copied
WORKDIR /user/src/app
COPY package*.json ./
# install app dependencies including 'devDependencies'
RUN npm install

# ---- Copy Files/Build ----
FROM dependencies AS build  
WORKDIR /usr/src/app
COPY . .
# Build react/vue/angular bundle static files
# RUN npm run build

# --- Release with Alpine ----
FROM node:11-alpine AS release  
# Create app directory
WORKDIR /user/src/app
# optional
# RUN npm -g install serve
COPY --from=dependencies /user/src/app/package.json ./
# Install app dependencies
RUN npm install --only=production
COPY --from=build /usr/src/app ./
# Run server
CMD ["node", "index.js"]