FROM golang:1.12-alpine3.9 AS base

RUN apk update && apk add --no-cache git ca-certificates

WORKDIR /go/src/users

# force the go compiler to use modules
ENV GO111MODULE=on

#  populate the module cache based on the go.{mod,sum} files.
COPY go.mod .
COPY go.sum .

# download all the dependencies that are specified in 
# the go.mod and go.sum file.
RUN go mod download

FROM base AS builder
# copy the rest of the source code
COPY . .

# and compile the project with appropriate tags to 
# turn off dynamic linking at runtime
RUN CGO_ENABLED=0 go build \
    -installsuffix 'static' \
    -o /app .

ENTRYPOINT ["/app"]

